#!/usr/bin/env python
"""
Created on Thu Nov 24 22:29:44 2016

@author: Admin
"""

import h5py

""" Reading Data from Files """

Q = str( 1 )

""" Position """
with h5py.File('Position_No' +Q+ '.h5', 'r') as hf:
    Position = hf['Position_Data'][:]

""" Energies """
with h5py.File('Energies_No' +Q+ '.h5', 'r') as hf:
    Energy = hf['Energy_Data'][:]

with h5py.File('Energy_Sum_No' +Q+ '.h5', 'r') as hf:
    Esum = hf['Esum_Data'][:]

""" Time """
with h5py.File('Time_No' +Q+ '.h5', 'r') as hf:
    Time = hf['Time_Data'][:]



